# Generated by Django 4.1.6 on 2023-02-28 16:31

from django.db import migrations
from django.contrib.auth.models import User


def create_profiles(apps, schema_editor):
    Profile = apps.get_model('chat', 'Profile')

    for user in User.objects.all():
        profile = Profile.objects.create(user=user)

class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_profile_status'),
    ]

    operations = [
    ]
