# Generated by Django 4.1.6 on 2023-03-01 16:30

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20230228_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatars/default-avatar.jpg', upload_to=chat.models.user_avatar_path),
        ),
    ]
