# Generated by Django 4.1.6 on 2023-03-01 16:32

from django.db import migrations
from django.core.files.storage import default_storage


def set_user_avatars(apps, schema_editor):
    Profile = apps.get_model('chat', 'Profile')

    for profile in Profile.objects.all():
        profile.avatar.save('default_avatar.png', default_storage.open('avatars/default_avatar.png'))
        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_profile_avatar'),
    ]

    operations = [
        migrations.RunPython(set_user_avatars),
    ]
