# Generated by Django 4.1.6 on 2023-03-01 16:40

from django.db import migrations
from django.core.files.storage import default_storage


def set_user_avatars(apps, schema_editor):
    Profile = apps.get_model('chat', 'Profile')
    Profile.objects.update(avatar='default_value')
    

class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20230301_2132'),
    ]

    operations = [
        migrations.RunPython(set_user_avatars)
    ]
